"""Generate or refresh docs/why.md, one section per change in the profile.

The point is somewhere to write *why*, with the *what* filled in already, so the
reasoning can be added a change at a time instead of in one sitting.

Run it with plain Python -- ``profile.py`` is a pure data module with no imports,
so this needs no Blender:

    python tools/gen_why.py

Safe to re-run. Existing prose is preserved: each section is keyed by a stable
``<!--id:...-->`` marker, the auto-written **What** line is regenerated, and
everything from **Why:** onward is left exactly as found. New profile entries are
appended as empty stubs; entries removed from the profile leave their section in
place, marked stale, rather than silently deleting writing.
"""

import importlib.util
import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PROFILE = os.path.join(ROOT, "extensions", "ez_preset", "profile.py")
OUT = os.path.join(ROOT, "docs", "why.md")

TODO = "_Not written yet._"

HEADER = """# Why

One section per change, with the *what* already filled in. Write the reasoning
under **Why:**.

Generated by `tools/gen_why.py`, which preserves anything written here. Re-run it
after adding entries to
[`extensions/ez_preset/profile.py`](../extensions/ez_preset/profile.py) and it
appends stubs for the new ones without touching existing prose.

Sections still marked `%s` are the backlog.
""" % TODO


def load_profile():
    spec = importlib.util.spec_from_file_location("ez_profile", PROFILE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")


def combo(entry):
    parts = [name for key, name in (("ctrl", "Ctrl"), ("alt", "Alt"),
                                    ("shift", "Shift"), ("oskey", "OS"))
             if entry.get(key)]
    return "+".join(parts + [str(entry.get("type", "?"))])


def sections(profile):
    """Yield (id, title, what) for every change in the profile."""
    for path, value, factory, note in profile.PREFERENCES:
        yield ("pref-" + slug(path), "`%s`" % path,
               "Set to `%r`, factory `%r`. %s" % (value, factory, note))

    for attr, value, factory, note in profile.KEYCONFIG_PREFERENCES:
        yield ("kcpref-" + slug(attr), "`%s` (keyconfig)" % attr,
               "Set to `%r`, factory `%r`. %s" % (value, factory, note))

    for module, attr, value, factory, note in profile.ADDON_PREFERENCES:
        yield ("addonpref-%s-%s" % (slug(module), slug(attr)),
               "`%s` → `%s`" % (module, attr),
               "Set to `%r`, factory `%r`. %s" % (value, factory, note))

    yield ("theme-" + slug(profile.THEME["extension_id"]),
           "Theme: %s" % profile.THEME["name"],
           "Version %s by %s, loaded from its extension folder."
           % (profile.THEME["version"], profile.THEME["author"]))

    for entry in profile.KEYMAP_ADD:
        yield ("km-add-%s-%s-%s" % (slug(entry["keymap"]), slug(combo(entry)),
                                    slug(entry["idname"])),
               "`%s` in %s — added" % (combo(entry), entry["keymap"]),
               "Runs `%s`. %s" % (entry["idname"], entry.get("note", "")))

    for entry in profile.KEYMAP_REBIND:
        yield ("km-move-%s-%s-%s" % (slug(entry["keymap"]),
                                     slug(combo(entry["to"])),
                                     slug(entry["idname"])),
               "`%s` in %s — moved" % (combo(entry["to"]), entry["keymap"]),
               "`%s` moved off `%s`. %s"
               % (entry["idname"], combo(entry["match"]), entry.get("note", "")))

    for entry in profile.KEYMAP_DISABLE:
        yield ("km-off-%s-%s-%s" % (slug(entry["keymap"]), slug(combo(entry)),
                                    slug(entry["idname"])),
               "`%s` in %s — switched off" % (combo(entry), entry["keymap"]),
               "Was `%s`. %s" % (entry["idname"], entry.get("note", "")))


SECTION_RE = re.compile(r"^#{2,3} .*?<!--id:([a-z0-9\-]+)-->[ \t]*$", re.M)


def parse_existing(text):
    """Map section id -> the prose written from **Why:** onward.

    Sections have to be bounded by the *next heading line*, not by the next id
    marker. The marker sits at the end of its heading, so splitting on markers
    makes each body run on and swallow the following section's title, which then
    gets written back into the previous section's reasoning.
    """
    found = {}
    matches = list(SECTION_RE.finditer(text))
    for index, match in enumerate(matches):
        start = match.end()
        end = (matches[index + 1].start()
               if index + 1 < len(matches) else len(text))
        body = text[start:end]
        marker = body.find("**Why:**")
        if marker != -1:
            found[match.group(1)] = body[marker + len("**Why:**"):].strip()
    return found


def main():
    profile = load_profile()
    existing = {}
    if os.path.exists(OUT):
        existing = parse_existing(io.open(OUT, encoding="utf-8").read())

    lines = [HEADER]
    live = set()
    written = 0
    for sid, title, what in sections(profile):
        live.add(sid)
        prose = existing.get(sid, TODO)
        if prose and prose != TODO:
            written += 1
        lines.append("## %s <!--id:%s-->\n" % (title, sid))
        lines.append("**What:** %s\n" % what.strip())
        lines.append("**Why:** %s\n" % prose)

    stale = sorted(set(existing) - live)
    if stale:
        lines.append("## Stale <!--id:stale-->\n")
        lines.append("These are no longer in the profile. Kept so the writing is "
                     "not lost; delete by hand once checked.\n")
        for sid in stale:
            lines.append("### `%s`\n" % sid)
            lines.append("%s\n" % existing[sid])

    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    total = len(live)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    print("  %d sections, %d with reasoning, %d to write"
          % (total, written, total - written))
    if stale:
        print("  %d stale section(s) kept: %s" % (len(stale), ", ".join(stale)))


main()
